name: 构建和发布香蕉时钟

on:
  push:
    tags:
      - 'v*'  # 只有当推送的标签以v开头时触发（如v1.0.0）
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest  # 使用Windows环境构建Windows应用
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: 安装依赖
      run: npm ci  # 使用ci比install更严格，确保依赖一致性
    
    - name: 构建应用
      run: npm run build  # 如果package.json中有build脚本
    
    - name: 打包Electron应用
      run: npm run dist  # 或 package 或 make，取决于您的electron-builder配置
    
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: banana-clock-installer
        path: |
          dist/*.exe
          dist/*.msi
          dist/*.zip
