name: Build Banana Clock
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install Dependencies
      run: npm install
    - name: Build Installer
      run: npm run package:win
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: banana-clock-installer
        path: dist/*.exe
